### ISSUE TITLE
Battlefield Support Asset Conversion

### ISSUE THREAD

**Issue by OftKilted** [Eudicods/outworlds-wastes#107]
Battlefield Support Asset Skills of 6 and 5 equate to 'Skill 4' and 'Skill 3' for standard values as BSP Assets are always counted as moving at a run. So their skill calculation includes their 'Always running or jumping'. 

The 'BSP Skill' == ((Gunnery + Piloting)/2) (Rounded Down) + Attacker Movement Modifier of 2 (because they are treated as 'running'). 

BSPs can't 'run', but always receive the higher of their TMM value or the terrain for the hex they are in and are counted as 'running' unless they are performing an Indirect Fire attack (where they loose their TMM and can't move but aren't counted as moving.) They're an 'odd duck' that doesn't use the Attacker Movement Modifier, except when Spotting. When it is counted as a '2'.

This would make the reference for the conversion seem odd because they're not actually 'skill 6' :

"When converting a unit in a force to an Asset, first compute the Asset skill level by taking the average of the Gunnery and Driving skills, rounding down, and adding 2. Only BV values for skill 5 and skill 6 are provided on the Asset cards, so unit skill levels may be temporarily degraded for a scenario to a higher skill level. Use the BV cost of the Asset at the computed skill level."

In CC:Mercenaries one can have both BSP and BV vehicle assets in a single force. BSPs are just basically 'temporary assets' as they can be swapped out from track(scenario) to track(scenario). Where the BV purchased units would be the 'permanent expensive' units with the crunchy rules.

**Comment by jeremylt** [comment]
> In CC:Mercenaries one can have both BSP and BV vehicle assets in a single force. BSPs are just basically 'temporary assets' as they can be swapped out from track(scenario) to track(scenario). Where the BV purchased units would be the 'permanent expensive' units with the crunchy rules.

That's not something Outworlds Wastes is doing. "Disposable" units that you can destroy without consequence isn't part of the design intent. The BSP Assets rules in Outworlds Wastes exist to allow commanders to run their combined arms units with the Total Warfare or BSP Assets rules, but in any case they must treat them as part of their force.

You can have a custom rule in your league/event though where disposable units can be purchased with BSP.

> This would make the reference for the conversion seem odd because they're not actually 'skill 6' :

I'm not sure of the confusion? As you said, the BSP Asset cards are Skill 5 or Skill 6 and always include a +2 to the base skill level to account for running, which is what the conversion rules also say to do. So a skill 4 TW unit would be a skill 6 BSP unit because its always running.
