### ISSUE TITLE
Resupply Costs? (Ammo?) Free ammo for all!

### ISSUE THREAD

**Issue by OftKilted** [Eudicods/outworlds-wastes#98]
Is ammunition and missiles free?

The managing a force sections don’t have any costs associated with re-arming a unit?

**Comment by OftKilted** [comment]
And what happens if folks choose to (or can’t afford to … or the scenario doesn’t let them) refill their ammo rounds for their gauss, AC, MG, SRM, NARC, AMS /weapons or systems?

**Comment by jeremylt** [comment]
Ammo is currently free since we're aiming for lightweight  logistics. Its more bookkeeping than is there currently as you now only need to know if each unit is OK, damaged, or destroyed. I'd be open to adding an Advanced Force Maintenance rule for ammo, though.

Chaos Campaign and the original Alpha Strike book has "Rearm Unit" costing 10 SP per unit for standard ammo and 50 per unit for special ammo. For the new Mercenary box Chaos Campaign we convert SP to C-bills for Outworlds Wastes at a ratio of 1-3,500. With that conversion, it costs a flat 35,000 C-bills for standard ammo and 175,000 C-bills for specialty ammo. In Alpha Strike there is a -1 modifier to damage at all brackets during a scenario if a unit is not rearmed. One could for Classic use that flat fee and assume 1/2 full bins if not refilled (empty bins if not for refiled two scenarios in a row) as a lightweight option or dig into the cost per ton given in Techmanual and such for more crunch.

**Comment by jeremylt** [comment]
Added optional rearm rule!
